version: '3.9'

services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_application
    command: ["sh", "./entrypoint.sh"]
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/social
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
